RI\AdminBundle\Entity\Admin:
    type: entity
    table: null
    repositoryClass: RI\AdminBundle\Repository\AdminRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
